version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Navigating to infra folder..."
      - cd infra # Change directory to the infra folder
      - npm install -g yarn
      - yarn

  pre_build:
    commands:
      - echo "Pre-build steps..."
      - yarn build # You can include a script in your package.json that handles pre-build tasks

  build:
    commands:
      - echo "Building the infrastructure..."
      - npx cdk synth # Synthesizes the CloudFormation template from your CDK code

  post_build:
    commands:
      - echo "Post-build steps..."
      - npx cdk deploy --require-approval never # Deploys the synthesized template

artifacts:
  files:
    - path/to/output # Specify output files or directories that need to be uploaded by CodeBuild
