name: Continuous Integration

# Define when the workflow should run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Jobs define what actions will run
jobs:
  build-and-push-web:
    runs-on: ubuntu-latest

    # Steps define the sequence of tasks that will be executed
    steps:
      - name: Checkout Web Folder from Repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: "web"
          sparse-checkout-cone-mode: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Specify your Node.js version

      - name: Get Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        working-directory: ./web
        run: yarn install

      - name: Build
        working-directory: ./web
        run: yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip Build Webapp Artifact
        working-directory: ./web
        run: zip -r ${{ github.sha }}.zip dist

      - name: Upload webapp artifact as SHA to S3
        working-directory: ./web
        run: aws s3 cp ./${{ github.sha }}.zip s3://loom-artifacts/

      - name: Upload webapp artifact as Latest to S3
        working-directory: ./web
        run: aws s3 cp ./${{ github.sha }}.zip s3://loom-artifacts/latest_web.zip

  build-and-push-infra:
    runs-on: ubuntu-latest

    # Steps define the sequence of tasks that will be executed
    steps:
      - name: Checkout Infra Folder from Repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: "infra"
          sparse-checkout-cone-mode: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip Build Infrastructure Artifact
        run: zip -r ${{ github.sha }}.zip .

      - name: Upload infrastructure artifact as Latest to S3
        run: aws s3 cp ./${{ github.sha }}.zip s3://loom-artifacts/latest_infra.zip
