name: Continuous Integration

# Define when the workflow should run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Jobs define what actions will run
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Steps define the sequence of tasks that will be executed
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Specify your Node.js version

      - name: Get Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn
        working-directory: ./web

      - name: List node_modules
        working-directory: ./web
        run: ls -la node_modules

      - name: Build
        run: yarn build
        working-directory: ./web

      # - name: Configure AWS credentials
      # uses: aws-actions/configure-aws-credentials@v1
      # with:
      #   aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   aws-region: ${{ secrets.AWS_REGION }}

      # - name: Upload artifact to S3
      #   run: aws s3 cp ./dist s3://your-artifact-bucket-name/${{ github.repository }}/${{ github.sha }}/ --recursive
